### ISSUE TITLE
attribute `lang="typescript"` breaks IntelliSense

### ISSUE THREAD

**Issue by HerringtonDarkholme** [octref/vetur#111]
VSCode version:  1.10.2 (1.10.2)
Vetur version: 0.5.6

Vanilla VSCode, with only Vetur enabled.

Reproduction:

Open a vue file. Add a `<script></script>` section.

If no `lang` is added, completion works.

<img width="1087" alt="screen shot 2017-03-29 at 2 51 23 pm" src="https://cloud.githubusercontent.com/assets/2883231/24442224/b7155c4a-148f-11e7-973b-33b4a79936a6.png">

However, `lang="typescript"` breaks this.
<img width="546" alt="screen shot 2017-03-29 at 2 52 33 pm" src="https://cloud.githubusercontent.com/assets/2883231/24442304/1b51f48e-1490-11e7-8a0b-1e34b808c576.png">

Since [typescriptMode](https://github.com/octref/vetur/blob/master/server/src/modes/typescriptMode.ts ) is added, I expect IntelliSense completion is supported in TypeScript block.

**Comment by octref** [comment]
Yes there is support for TS since #94, but it hasn't been released yet because there are some rough edges that I want to handle. There are lot of completions that don't make sense, and I think the standard is `lang="ts"`...

I'm looking towards to release 0.6 which finishes IntelliSense described in #26 and integrates #94 better.

![image](https://cloud.githubusercontent.com/assets/4033249/24446880/19f2a33e-143d-11e7-9a15-e392dba66441.png)
