### ISSUE TITLE
Some of the Typescript not respecting noImplicitAny from project tsconfig.json file

### ISSUE THREAD

**Issue by brianjorden** [octref/vetur#140]
It seems there is a slightly inconsistent behavior of Typescript parsing and the usage of the project's local tsconfig.json settings. The part I've really noticed is the noImplicitAny flag being interpreted in some, but not all places. The screenshot below shows a couple arbitrary function definitions inside and outside a component's `export default`. Based on reading some of the comments in the Typescript pull request, it seems there are some assumptions that have to be made about the default export, and it might be tied to that. I've also included a couple declarations that show appropriate errors when the type IS given, so it is obviously trying to validate things. The difference is between `thing2` and `stuff2`.

![image](https://cloud.githubusercontent.com/assets/12365487/25293097/33641a24-26a7-11e7-9374-7678d4bc268f.png)

**Comment by octref** [comment]
Would you mind sharing the test project with me?

**Comment by octref** [comment]
Also see https://github.com/octref/vetur/issues/159#issuecomment-297608690

**Comment by octref** [comment]
I'll track this in #159.

**Comment by evenfrost** [comment]
Just faced this one recently. TypeScript checking with `noImplicitAny` is not working in .vue files for this specific case, but others do.

Tested on [`vue-cli`](https://github.com/vuejs/vue-cli) with TypeScript config.

Here, VS Code outputs only 1 typechecking error (though `event` in `onClick` method has implicit `any` type):

![screen1](https://user-images.githubusercontent.com/3055750/38361856-7b4b022e-38d7-11e8-9464-d962c41984df.png)

However, TypeScript compiler correctly outputs 2 errors:

![screen2](https://user-images.githubusercontent.com/3055750/38361880-908e95ec-38d7-11e8-92d9-fa733800ef85.png)

@octref as this issue and #159 are now closed, https://github.com/vuejs/vetur/issues/170 is not quite related to TypeScript itself but to TSLint support and https://github.com/vuejs/vetur/issues/188 seems to not have TypeScript-specific tasks in it, I just wanted to make sure this issue is still being tracked.
