### ISSUE TITLE
按用法配置后，html部分格式化出错

### ISSUE THREAD

**Issue by linmodev** [octref/vetur#38]
按照readme配置好后，可以正常工作了，但是html代码不能正常格式化
```javascript
"files.associations": {
  "*.vue": "vue"
}
```
如果不配置上面这个选项，格式化是正常的，但同时css属性完全不会出现智能提示
![代码格式化如下](http://odhsaddf1.bkt.clouddn.com/QQ%E5%9B%BE%E7%89%8720170214102709.png)

**Comment by octref** [comment]
Can you use English, please?

Embedded formatter support isn't available yet and is tracked in #20.

**Comment by linmodev** [comment]
@octref Thanks.
My English is too bad.

**Comment by octref** [comment]
It's fine, I can get what you are saying. Just keep trying and you'll become better :-)

> but properly formatted HTML code

I guess you meant you **can't** properly format html code.

**Comment by linmodev** [comment]
@octref Thanks, I will learn English well.
Hope that the next version support Embedded formatter

**Comment by octref** [comment]
Sorry -- do you have any html formatter installed?

Because VSCode's html formatter seems to be working for me correctly:

![format](https://cloud.githubusercontent.com/assets/4033249/22957641/a7ef82a4-f2f7-11e6-9254-8de61887f3ee.gif)

VSCode currently only comes with html and js formatter it seems, so when you try to format, I'd suggest just format the `<template>` and `<script>` regions for now.

**Comment by linmodev** [comment]
Before I installed other html formatter extension, but i remove it and i don't find option that format selection code. When I save my file by `ctrl+s`, the editor will format code auto.
![My VSCode's html formatter don't work correctly yet](http://odhsaddf1.bkt.clouddn.com/GIF.gif)

**Comment by octref** [comment]
I think you are running into the same problem as #39. Inline style messed up with html formatter. I'll look into it and track it in #39.

**Comment by linmodev** [comment]
You can see this plugin ![Yours is conflict with this plugin ](http://odhsaddf1.bkt.clouddn.com/QQ%E5%9B%BE%E7%89%8720170215104442.png)
